# Generated by Django 6.1.1 on 2026-09-15 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_classsession_options_and_more'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academy.classsession'),
        ),
    ]
