# Generated by Django 6.0.7 on 2026-09-15 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Academy Attendance Policy', max_length=100)),
                ('early_window_minutes', models.PositiveIntegerField(default=15, help_text='Allow students to join up to N minutes before class start')),
                ('late_cutoff_minutes', models.PositiveIntegerField(default=5, help_text='Joining within N minutes of start is PRESENT; after this is marked LATE')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('google_meet_link', models.URLField(default='https://meet.google.com/abc-defg-hij', help_text='Google Meet link for this session')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Live / Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.instructorprofile')),
            ],
            options={
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_entries', to='academy.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_session_entries', to='core.studentprofile')),
            ],
            options={
                'unique_together': {('class_session', 'student')},
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scheduled_classes', through='academy.ClassStudent', to='core.studentprofile'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='courses', to='core.studentprofile')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.instructorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academy.course'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField(blank=True, help_text='Key takeaways and outline')),
                ('content', models.TextField(blank=True, help_text='Lesson notes, syntax explanations, and examples')),
                ('video_url', models.URLField(blank=True, help_text='Embedded video explanation / tutorial link')),
                ('duration_mins', models.PositiveIntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.course')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Infographic / Diagram'), ('WORKSHEET', 'Exercise Worksheet'), ('NOTES', 'Lecture Summary'), ('CODE', 'Code Starter / Solution'), ('OTHER', 'Educational File')], default='PDF', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('external_link', models.URLField(blank=True, help_text='Optional external Drive / GitHub / Resource URL')),
                ('is_published', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.lesson')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Session Recording', max_length=200)),
                ('recording_url', models.URLField(help_text='Google Meet or Cloud Recording Link')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='academy.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='ABSENT', max_length=20)),
                ('join_time', models.DateTimeField(blank=True, help_text='Timestamp when student clicked Join Class', null=True)),
                ('click_join_event', models.BooleanField(default=False)),
                ('manual_override', models.BooleanField(default=False, help_text='Flag if attendance was updated manually by instructor/admin')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.studentprofile')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academy.classsession')),
            ],
            options={
                'ordering': ['-class_session__scheduled_date', 'student__user__first_name'],
                'unique_together': {('class_session', 'student')},
            },
        ),
    ]
