# Generated by Django 6.1.1 on 2026-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsession',
            options={'ordering': ['scheduled_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='classsession',
            name='session_number',
            field=models.PositiveIntegerField(default=1, help_text='رقم الحصة في الكورس (حصة 1، 2...)'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='شرح الحصة وملخص ما تم إنجازه (يضيفه المدرس بعد انتهاء الحصة)'),
        ),
        migrations.AddField(
            model_name='course',
            name='default_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='default_meet_link',
            field=models.URLField(blank=True, default='https://meet.google.com/abc-defg-hij', help_text='رابط جوجل ميت المعتمد لحصص الكورس'),
        ),
        migrations.AddField(
            model_name='course',
            name='default_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_days',
            field=models.CharField(blank=True, default='', help_text='أيام الحصص مفصولة بفواصل، مثل: SAT,TUE', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='تاريخ بداية الكورس (أول حصة)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_sessions_count',
            field=models.PositiveIntegerField(default=8, help_text='عدد الحصص الإجمالي المطلوب جدولتها'),
        ),
    ]
