# Generated by Django 6.1.1 on 2026-09-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_classsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='summary_file',
            field=models.FileField(blank=True, help_text='ملف أو ملزمة شرح الحصة (PDF / مستندات)', null=True, upload_to='session_summaries/'),
        ),
    ]
